# Generated by Django 6.0.2 on 2026-02-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_role",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
