# Generated by Django 6.0.2 on 2026-02-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_administrator_user_alter_airlinecompany_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="credit_card_no",
        ),
    ]

