# Generated by Django 6.0.2 on 2026-02-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customer_credit_card_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone_no",
        ),
    ]

