# Generated by Codex on 2026-02-26

import django.db.models.deletion
from django.db import migrations, models


def backfill_pdf_schema_requirements(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    UserRole = apps.get_model("accounts", "UserRole")
    Customer = apps.get_model("accounts", "Customer")
    AirlineCompany = apps.get_model("accounts", "AirlineCompany")
    Administrator = apps.get_model("accounts", "Administrator")

    customer_role, _ = UserRole.objects.get_or_create(role_name="Customer")
    airline_role, _ = UserRole.objects.get_or_create(role_name="Airline Company")
    admin_role, _ = UserRole.objects.get_or_create(role_name="Administrator")

    for customer in Customer.objects.select_related("user"):
        user = customer.user
        if user and user.user_role_id is None:
            user.user_role = customer_role
            user.save(update_fields=["user_role"])

    for airline in AirlineCompany.objects.select_related("user"):
        user = airline.user
        if user and user.user_role_id is None:
            user.user_role = airline_role
            user.save(update_fields=["user_role"])

    for admin in Administrator.objects.select_related("user"):
        user = admin.user
        if user and user.user_role_id is None:
            user.user_role = admin_role
            user.save(update_fields=["user_role"])

    for customer in Customer.objects.all():
        updates = {}
        if not customer.address:
            updates["address"] = "Unknown address"
        if not customer.phone_no:
            updates["phone_no"] = f"PH{customer.id:013d}"[-15:]
        if not customer.credit_card_no:
            updates["credit_card_no"] = f"{customer.id:013d}"[-13:]
        if updates:
            Customer.objects.filter(id=customer.id).update(**updates)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_airlinecompany_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_card_no",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.userrole",
            ),
        ),
        migrations.RunPython(
            backfill_pdf_schema_requirements, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_no",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="credit_card_no",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
