# Generated by Codex on 2026-02-24
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_ticket_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="cabin_class",
            field=models.CharField(
                choices=[("ECONOMY", "Economy"), ("BUSINESS", "Business")],
                default="ECONOMY",
                max_length=16,
            ),
        ),
    ]
