# Generated by Codex on 2026-02-26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_add_cabin_class"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
    ]

