# Generated by Codex on 2026-02-26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_remove_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("flight", "customer")},
        ),
    ]
