# Generated by Codex on 2026-02-26
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0005_restore_unique_ticket_per_customer_flight"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
    ]
