# Generated by Django 6.0.2 on 2026-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_remove_unique_ticket_per_customer_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                ],
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
