# Generated by Django 6.0.2 on 2026-02-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_user_role_delete_userrole"),
        ("flights", "0001_initial"),
        ("geo", "0002_alter_country_options_remove_country_flag_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="destination_country",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="origin_country",
        ),
        migrations.AddField(
            model_name="flight",
            name="destination_airport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arriving_flights",
                to="geo.airport",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="origin_airport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departing_flights",
                to="geo.airport",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="airline_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flights",
                to="accounts.airlinecompany",
            ),
        ),
    ]
