# Generated by Django 6.0.2 on 2026-02-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_remove_flight_destination_country_and_more"),
    ]

    operations = []
