# Generated by Codex on 2026-02-24
from django.db import migrations, models
import django.core.validators
from django.db.models import F


def populate_cabin_defaults(apps, schema_editor):
    Flight = apps.get_model("flights", "Flight")
    Flight.objects.all().update(
        economy_seats=F("remaining_tickets"),
        remaining_economy_tickets=F("remaining_tickets"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0003_add_stored_procedures"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="economy_seats",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="business_seats",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="remaining_economy_tickets",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="remaining_business_tickets",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="economy_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="flight",
            name="business_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(populate_cabin_defaults, migrations.RunPython.noop),
    ]
