# Generated by Codex on 2026-02-26

from django.db import migrations


def create_remaining_stored_procedures(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION get_airline_by_username(p_username TEXT)
            RETURNS TABLE(id BIGINT)
            LANGUAGE sql
            AS $$
                SELECT a.id
                FROM accounts_airlinecompany AS a
                INNER JOIN accounts_user AS u ON u.id = a.user_id
                WHERE LOWER(u.username) = LOWER(p_username)
                LIMIT 1;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION get_customer_by_username(p_username TEXT)
            RETURNS TABLE(id BIGINT)
            LANGUAGE sql
            AS $$
                SELECT c.id
                FROM accounts_customer AS c
                INNER JOIN accounts_user AS u ON u.id = c.user_id
                WHERE LOWER(u.username) = LOWER(p_username)
                LIMIT 1;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION get_user_by_username(p_username TEXT)
            RETURNS TABLE(id BIGINT)
            LANGUAGE sql
            AS $$
                SELECT u.id
                FROM accounts_user AS u
                WHERE LOWER(u.username) = LOWER(p_username)
                LIMIT 1;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION get_flights_by_parameters(
                p_origin_country_id INTEGER,
                p_destination_country_id INTEGER,
                p_date DATE
            )
            RETURNS TABLE(id BIGINT)
            LANGUAGE sql
            AS $$
                SELECT f.id
                FROM flights_flight AS f
                INNER JOIN geo_airport AS origin_airport
                    ON origin_airport.id = f.origin_airport_id
                INNER JOIN geo_airport AS destination_airport
                    ON destination_airport.id = f.destination_airport_id
                WHERE origin_airport.country_id = p_origin_country_id
                  AND destination_airport.country_id = p_destination_country_id
                  AND f.departure_time::date = p_date
                ORDER BY f.departure_time ASC;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION get_flights_by_airline_id(p_airline_id BIGINT)
            RETURNS TABLE(id BIGINT)
            LANGUAGE sql
            AS $$
                SELECT f.id
                FROM flights_flight AS f
                WHERE f.airline_company_id = p_airline_id
                ORDER BY f.departure_time ASC;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION get_arrival_flights(p_country_id INTEGER)
            RETURNS TABLE(id BIGINT)
            LANGUAGE sql
            AS $$
                SELECT f.id
                FROM flights_flight AS f
                INNER JOIN geo_airport AS destination_airport
                    ON destination_airport.id = f.destination_airport_id
                WHERE destination_airport.country_id = p_country_id
                  AND f.landing_time BETWEEN NOW() AND (NOW() + INTERVAL '12 hours')
                ORDER BY f.landing_time ASC;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION get_departure_flights(p_country_id INTEGER)
            RETURNS TABLE(id BIGINT)
            LANGUAGE sql
            AS $$
                SELECT f.id
                FROM flights_flight AS f
                INNER JOIN geo_airport AS origin_airport
                    ON origin_airport.id = f.origin_airport_id
                WHERE origin_airport.country_id = p_country_id
                  AND f.departure_time BETWEEN NOW() AND (NOW() + INTERVAL '12 hours')
                ORDER BY f.departure_time ASC;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION get_tickets_by_customer(p_customer_id BIGINT)
            RETURNS TABLE(id BIGINT)
            LANGUAGE sql
            AS $$
                SELECT t.id
                FROM tickets_ticket AS t
                WHERE t.customer_id = p_customer_id
                ORDER BY t.id ASC;
            $$;
            """
        )


def drop_remaining_stored_procedures(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP FUNCTION IF EXISTS get_airline_by_username(TEXT);")
        cursor.execute("DROP FUNCTION IF EXISTS get_customer_by_username(TEXT);")
        cursor.execute("DROP FUNCTION IF EXISTS get_user_by_username(TEXT);")
        cursor.execute(
            "DROP FUNCTION IF EXISTS get_flights_by_parameters(INTEGER, INTEGER, DATE);"
        )
        cursor.execute("DROP FUNCTION IF EXISTS get_flights_by_airline_id(BIGINT);")
        cursor.execute("DROP FUNCTION IF EXISTS get_arrival_flights(INTEGER);")
        cursor.execute("DROP FUNCTION IF EXISTS get_departure_flights(INTEGER);")
        cursor.execute("DROP FUNCTION IF EXISTS get_tickets_by_customer(BIGINT);")


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0004_add_cabin_fields"),
    ]

    operations = [
        migrations.RunPython(
            create_remaining_stored_procedures,
            drop_remaining_stored_procedures,
        ),
    ]
