# Generated by Django 6.0.2 on 2026-02-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="country",
            name="flag_image",
        ),
        migrations.AddField(
            model_name="country",
            name="flag_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="country",
            name="iso2",
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iata_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=3
                    ),
                ),
                (
                    "icao_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=4
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=128)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="airports",
                        to="geo.country",
                    ),
                ),
            ],
            options={
                "ordering": ["country__name", "city", "name"],
            },
        ),
    ]
